### ISSUE TITLE
Node ON and OFF:Message Format and Topic info 

### ISSUE THREAD

**Issue by anshulkatta** [Team-SDIoT/EazyExit-Node#1]
**# FROM APP to NODE**

ID* corresponds to Hash SHA ( whatever is generated at node's end , the app will save that string as and identify it as)

1) For Every Node , the message from App will go to below Topic - 

        TOPIC - myHome

2) the Message Format are as below - (CAPS do matter)

        ID:ON for ON and ID:OFF for OFF

For eg.  If suppose the ID is 192.168.0.3 , then the message goes to Node to Turn it on  is

**192.168.0.3:ON**

============================================================

**# FROM NODE to APP**

1) The Node has to reply on the same topic  **TOPIC - EazyExit/ACK** 

2) The Node has to reply with same message it received from the APP and process the ON or OFF  
     successfully  - 

    `ID:ON for ON and ID:OFF for OFF`

**For later as discussed , the username and password will be passed in each message for security and abuse of vulnerability**

**Comment by iayanpahwa** [comment]
PR generated #3
