### ISSUE TITLE
Master Switch : Topic and Message Format

### ISSUE THREAD

**Issue by anshulkatta** [Team-SDIoT/EazyExit-Node#2]
# FROM APP to NODE  

ID* corresponds to Hash SHA ( whatever is generated at node's end , the app will save that string as and identify it as)

1) For All Nodes , the message from App will go to below Topic -

       TOPIC - myHome
2) the Message Format are as below - (CAPS do matter)

       ON & OFF 

    For eg. If suppose the ID is 192.168.0.3 , then the message goes to Node to Turn it on is

      `ON`

============================================================

# FROM NODE to APP

The Node has to reply on the  **TOPIC - EazyExit/ACK**

The Node has to reply with  message if it process the ON or OFF successfully -

`ID:ON for ON and ID:OFF for OFF`

**For later as discussed , the username and password will be passed in each message for security and abuse of vulnerability**

**Comment by iayanpahwa** [comment]
PR generated #3
